services:
  db:
    image: postgres:17
    container_name: tp2_web2_db
    environment:
      POSTGRES_DB: tp2_web2
      POSTGRES_USER: webii_tp2
      POSTGRES_PASSWORD: webii_tp2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: